### ISSUE TITLE
AudioStreamPlayer not working on ubuntu

### ISSUE THREAD

**Issue by pedroteosousa** [pedroteosousa/Teleporter#23]
... or something

**Comment by thiagestrela** [comment]
Fixed on cf29734a8cebc45a552f4b030f81456441aba98e

**Comment by thiagestrela** [comment]
cf29734a8cebc45a552f4b030f81456441aba98e

**Comment by thiagestrela** [comment]
Fixed on cf29734a8cebc45a552f4b030f81456441aba98e
