### ISSUE TITLE
Choosing ball by number doesn't work on tutorial levels

### ISSUE THREAD

**Issue by PedroBortolli** [pedroteosousa/Teleporter#24]
On tutorial level 2, choosing ball by number doesn't work at the part of the tutorial that teaches how to switch between balls. Only scrolling up/down does the job.

**Comment by pedroteosousa** [comment]
It's working fine here, could you give some steps to replicate the issue?

**Comment by PedroBortolli** [comment]
Just before tutorial level 2 ends, the game suggests "Oh, scroll up/down to select ball. Choose by pressing 1, 2, 3, etc accordingly too"

At that moment you can only scroll up/down to select balls. However, after that message you can indeed choose by the number keys.
