### ISSUE TITLE
Only continue after user input on Tutorial Level 3

### ISSUE THREAD

**Issue by PedroBortolli** [pedroteosousa/Teleporter#27]
On tutorial level 3, after you break the wall using a destructible ball, the game only continues to the next tutorial message after player inputs something (mouse move, press a button, etc).

If the player only destroys the wall and doesn't do anything else the game will be stuck at that part

**Comment by pedroteosousa** [comment]
Won't the player need to teleport to the exit to go to the next level? I'm not sure I follow you.

**Comment by PedroBortolli** [comment]
@pedroteosousa The player may be mislead by the fact that if he doesn't do anything after he breaks the wall i.e. he may think that he has to wait for something in the game to appear before continuing
