### ISSUE TITLE
Buggy collision between Kinematic Bodies

### ISSUE THREAD

**Issue by pedroteosousa** [pedroteosousa/Teleporter#6]
Sometimes only one of the bodies detect the collision, so the physics isn't realistic, to put it mildly

**Comment by thiagestrela** [comment]
Could you give an example of a situation that bug occurs?

**Comment by pedroteosousa** [comment]
Shoot a pool ball in a direction, and then a faster pool ball in the same direction. Second one will bounce, while first one stays the same

**Comment by pedroteosousa** [comment]
Another problem is when two balls collide and stay put for a moment, that happens because both are detecting collision more than once, and keep on changing their direction.

**Comment by thiagestrela** [comment]
I think [this](https://godotengine.org/qa/14411/how-to-get-a-kinematicbody2ds-colliders-collision) can be useful! :)

**Comment by thiagestrela** [comment]
[this](https://github.com/Kermer/Godot/wiki/tut_simple-collision) too.

**Comment by pedroteosousa** [comment]
Try again
